/*

 CLUBFRONT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\John\Desktop\Gamejam 2023\Fall23Gamejam\Gamejam Tilesets\Tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 27
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ClubFrontWidth 20
#define ClubFrontHeight 18
#define ClubFrontBank 0

extern unsigned char ClubFront[];

/* End of CLUBFRONT.H */
