/*

 ENDSCREENMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 11 x 4
   Tile set      : C:\Users\John\Desktop\Gamejam 2023\Fall23Gamejam\Gamejam Tilesets\Alphabet.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define EndScreenWidth 11
#define EndScreenHeight 4
#define EndScreenBank 0

extern unsigned char EndScreen[];

/* End of ENDSCREENMAP.H */
