/*

 GAMEOVERMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 9 x 1
   Tile set      : C:\Users\John\Desktop\Gamejam 2023\Fall23Gamejam\Gamejam Tilesets\Alphabet.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define GameOverMapWidth 9
#define GameOverMapHeight 1
#define GameOverMapBank 0

unsigned char GameOverMap[] =
{
  0x06,0x00,0x0C,0x04,0x7F,0x0E,0x15,0x04,0x11
};

/* End of GAMEOVERMAP.C */
