/*

 LEVELTWOTUTORIAL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 5
   Tile set      : C:\Users\John\Desktop\Gamejam 2023\Fall23Gamejam\Gamejam Tilesets\Tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 27
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define LevelTwoTutorialWidth 20
#define LevelTwoTutorialHeight 5
#define LevelTwoTutorialBank 0

extern unsigned char LevelTwoTutorial[];

/* End of LEVELTWOTUTORIAL.H */
