/*

 LEVELTWOSTARTMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 9 x 2
   Tile set      : C:\Users\John\Desktop\Gamejam 2023\Fall23Gamejam\Gamejam Tilesets\Alphabet.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define LevelTwoStartMapWidth 9
#define LevelTwoStartMapHeight 2
#define LevelTwoStartMapBank 0

unsigned char LevelTwoStartMap[] =
{
  0x0B,0x04,0x15,0x04,0x0B,0x7F,0x13,0x16,0x0E,0x03,
  0x00,0x0D,0x02,0x04,0x7F,0x0E,0x05,0x05
};

/* End of LEVELTWOSTARTMAP.C */
