/*

 LEVELONETUTORIALMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 3
   Tile set      : C:\Users\John\Desktop\Gamejam 2023\Fall23Gamejam\Gamejam Tilesets\Alphabet.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define LevelOneTutorialMapWidth 8
#define LevelOneTutorialMapHeight 3
#define LevelOneTutorialMapBank 0

unsigned char LevelOneTutorialMap[] =
{
  0x1A,0x0C,0x0E,0x15,0x04,0x7F,0x7F,0x7F,0x7F,0x7F,
  0x7F,0x7F,0x7F,0x7F,0x7F,0x7F,0x12,0x0D,0x04,0x00,
  0x0A,0x7F,0x08,0x0D
};

/* End of LEVELONETUTORIALMAP.C */
