/*

 LEVELONETUTORIALMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 3
   Tile set      : C:\Users\John\Desktop\Gamejam 2023\Fall23Gamejam\Gamejam Tilesets\Alphabet.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define LevelOneTutorialMapWidth 8
#define LevelOneTutorialMapHeight 3
#define LevelOneTutorialMapBank 0

extern unsigned char LevelOneTutorialMap[];

/* End of LEVELONETUTORIALMAP.H */
