/*

 PRESSSTARTMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 11 x 1
   Tile set      : C:\Users\John\Desktop\Gamejam 2023\Fall23Gamejam\Gamejam Tilesets\Alphabet.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/


unsigned char PressStartMap[] =
{
  0x0F,0x11,0x04,0x12,0x12,0x7F,0x12,0x13,0x00,0x11,
  0x13
};

/* End of PRESSSTARTMAP.C */
